name: Tests

on:
  push:
    branches: [ "main" ]
    paths: ['src/**', 'tests/**']
  pull_request:
    branches: [ "main" ]
    paths: ['src/**', 'tests/**']

jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
